apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: staticwebapp
  name: staticwebapp
spec:
  selector:
    matchLabels:
      app: staticwebapp
  template:
    metadata:
      labels:
        app: staticwebapp
    spec:
      containers:
      - image: aminegongi/staticwebapp:latest
        name: staticwebapp
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: staticwebapp
