apiVersion: v1
kind: Service
metadata:
  labels:
    app: staticwebapp
  name: staticwebapp
spec:
  type: NodePort
  ports:
  - name: "staticwebappservice"
    port: 80
    targetPort: 80
    nodePort: 30008
  selector:
    app: staticwebapp
